apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tanzu-rabbitmq
  annotations:
    #ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: resource-overlay
    # ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: rabbitmq-validating-webhook-configuration-overlay # annotation
spec:
  serviceAccountName: rabbitmq-operator # Replace with service account name
  packageRef:
    refName: rabbitmq.tanzu.vmware.com
    versionSelection:
      constraints: 1.3.1 #1.2.2 # Replace with release version
#   values:
#   - secretRef:
#       name: rabbitmq-validating-webhook-configuration-overlay
# # ---
# # apiVersion: v1
# kind: Secret
# metadata:
#   name: tanzu-rabbitmq-values
# stringData:
#   values.yml: |
#     ---
#     namespace: rabbitmq-operator # Replace with the target install namespace
